---
- hosts: all
  sudo : true
  vars_files:
    - ../vars_common/{{machine}}.yml
    - vars/{{machine}}.yml


  tasks:
    - set_fact:
        machine: "{{machine}}"

# base
    - hostname: name={{hostname}}

    - name: set networking
      template: src="files/interfaces/eth1.cfg.j2" dest="/etc/network/interfaces.d/eth1.cfg"
    - name: start interfaced
      shell: ifup eth1
